# Workflow name (appears in GitHub UI)
name: CI

# When to run this workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs to run
jobs:
  test:
    # Which operating system to use
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Get the code from GitHub
    - uses: actions/checkout@v3
    
    # Step 2: Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21
    
    # Step 3: Download dependencies
    - name: Download dependencies
      run: go mod download
    
    # Step 4: Run tests
    - name: Run tests
      run: go test ./...
    
    # Step 5: Build the application
    - name: Build
      run: go build cmd/server/main.go
    
    # Step 6: Build Docker image (optional)
    - name: Build Docker image
      run: docker build -t go-docker-starter .